ros-drivers/velodyne

velodyne_pointcloud/scripts/gen_calibration.py
`min_intensity` and `max_intensity` should be saved as integer, otherwise [this line](https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/src/lib/calibration.cc#L72) will break
=> fixed gen_calibration min/max intensity type

velodyne_pointcloud/src/lib/rawdata.cc
So here is the full rawdata.cc file with the corrected codes as I suggested in the Issue#50. Like I explained there, I changed some of the expressions for the calculations of x, y, z and we got in our Tests a better result, which is show down here:
the result with the original codes:
the result with the new codes:
the result with the original codes:
the result with the new codes:
the result with the original codes:
the result with the new codes:
=> Added vertical sin angle correction

velodyne_pointcloud/src/lib/rawdata.cc
Fix for VLP16 unpack:
For interpolated azimuth values between 35999.5 and 36000.0 the nested round(fmod())
yields a value of 36000 which is invalid and overflows the pre-computed sin/cos arrays,
since they only go form 0..35999
I switched the order of rounding and modulo so this doesn't happen.
=> Fixed azimuth overflow bug.

velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/src/driver/driver.cc, velodyne_driver/src/lib/input.cc
Hello,
we have a scenario here with multiple velodynes in one network. So we developed a patch for your driver, which allows working with multiple velodyne LIDARs.
It adds the parameter "device_ip" to the velodyne_driver node. With the parameter one can select which LIDAR's packets  should be processed and published by the node. Default behaviour is unchanged (process all packets).
Hope you find it useful.
Denis
=> support for multiple velodynes

velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/src/driver/driver.cc, velodyne_driver/src/lib/input.cc
This is an improvement on @ddillenberger implementation of the multi velodyne support. From what I understand from his design, and from what I experienced today on my setup (4 16-beam velodynes), @ddillenberger code allows to read data from one and only one laser at the same time.
With this pull request, we add support for reading data simultaneously from several lidars at the same time. Each lidar must be configured with a separate IP address and to broadcast on a separate port.
With this code, we were able to read from 4 velodyne at the same time.
Credits also go to @ddillenberger and @ahendrix for this pull request.
=> support for multiple velodynes (improved)

velodyne_pointcloud/src/lib/rawdata.cc
I think that `dsr` was unused. See line 317: 
for (int dsr=0; ...
=> Remove unused variable

velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h, velodyne_pointcloud/src/lib/rawdata.cc
The timing constants for theVLP-16 azimuth calculation are of type `int` instead of `float` or `double`. Therefore, the computed point cloud is distorted.
Apart from that, I rearranged a few comments. Feel free to include these latter changes or not.
=> Correct important data type error for VLP-16

.gitignore, velodyne_pointcloud/src/conversions/transform.cc, velodyne_pointcloud/src/lib/calibration.cc, velodyne_pointcloud/src/lib/rawdata.cc
Previously, the console log always told you that velodyne_pointcloud interprets data as VLP-16 data, no matter what the calibration file. When you load a HDL-64E calibration file, for example, you get the following output on the console:
```
...
[ INFO] [1455797371.476088236]: laser_ring[2] = 58, angle = 0.00969335
[ INFO] [1455797371.476152253]: laser_ring[3] = 59, angle = 0.0152117
[ INFO] [1455797371.476215947]: laser_ring[24] = 60, angle = 0.0211378
[ INFO] [1455797371.476280336]: laser_ring[25] = 61, angle = 0.0280837
[ INFO] [1455797371.476343884]: laser_ring[28] = 62, angle = 0.032985
[ INFO] [1455797371.476407944]: laser_ring[29] = 63, angle = 0.0387013
[ INFO] [1455797371.477147818]: Data will be processed as a VLP-16...num_lasers: 64
```
Obviously, the data will not `be …
=> Fix output of calibration data onto console

velodyne_pointcloud/src/lib/calibration.cc
I had need to import a file which contained floats instead of ints for the `min_intensity` and `max_intensity` fields in a calibration file. So the first thing this pr does is change how those values are extracted from YAML. First it tries to get them as ints, but if that throws an InvalidScalar exception, then I try to put it in a float and if that works I cast the floor the float to the int storage and warn once.
I believe this will also address https://github.com/ros-drivers/velodyne/issues/45. It will attempt to extract `horiz_offset_correction` from the YAML file and if it is not there, then it defaults to `0`, which I believe is the consensus that was reached in #45.
=> allow floats in min/max_intensity and make horiz_offset_correction optional

velodyne_pointcloud/src/lib/rawdata.cc
I had to reverse engineered your driver for some calibration and, when expressing your equations with rotation matrix, realized that some signs were inverted. I could send you the equations but it's also consistent with the following:
- [Velodyne manual](http://www.velodynelidar.com/lidar/products/manual/HDL-64E%20S3%20manual.pdf) p. 44
```
xyDistance = distance * cosVertAngle;// — vOffsetCorr * sinVertAngle;
```
- this [calibration paper](http://cdn.intechweb.org/pdfs/23811.pdf), eq. (4)
=> Sign inversion in some equations

.gitignore, velodyne_pointcloud/CMakeLists.txt, velodyne_pointcloud/cfg/CloudNode.cfg, velodyne_pointcloud/cfg/TransformNode.cfg, velodyne_pointcloud/src/conversions/CMakeLists.txt, velodyne_pointcloud/src/conversions/convert.cc, velodyne_pointcloud/src/conversions/convert.h, velodyne_pointcloud/src/conversions/transform.cc, velodyne_pointcloud/src/conversions/transform.h
Until now, transform_node does neither read parameters other than frame_id from the command line nor does it expose these parameters via dynamic reconfigure. As parameters like max_range and view_width are initialized to zero, transform_node always returns an empty point cloud:
`rosrun velodyne_pointcloud transform_node _calibration:=ros/calibration/velodyne_64e.yaml`
The commits in this pull request alter transform_node's behavior: Now, the node launches an reconfigure server just as cloud_node. The default configuration values are the same as in cloud_node. In addition to cloud_node, transform node exposes the frame_id parameter to reconfiguration. Now, the output looks like this:
`rosrun velodyne_pointcloud transform_node _calibration:=ros/calibration/velodyne_64e.yaml`
=> Dynamic reconfiguration of transform_node

velodyne_driver/CMakeLists.txt, velodyne_driver/cfg/VelodyneNode.cfg, velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/package.xml, velodyne_driver/src/driver/CMakeLists.txt, velodyne_driver/src/driver/driver.cc, velodyne_driver/src/driver/driver.h, velodyne_driver/src/lib/input.cc, velodyne_pointcloud/src/conversions/transform.cc
This allows the user to compensate constant time offsets when velodyne_driver runs in live mode. The feature is highly valuable for the synchronization of multi-sensor setups. The chosen time_offset (parameter: '~time_offset') is added to the calculated time stamps, so that this parameter should typically be negative. For my setup, ~time_offset is in the range of -20ms. The parameter can be changed during runtime via dynamic_reconfigure. The naming of the parameter is according to the naming of this functionality in other nodes such as urg_node (hokuyo) and the openni-drivers.
=> Add dynamic latency configuration to velodyne_driver

velodyne_driver/package.xml
The driver currently supports all Velodyne LiDAR models.
=> update velodyne_driver package description to include all models

velodyne_pointcloud/src/conversions/colors.cc, velodyne_pointcloud/src/lib/rawdata.cc
Building the velodyne drivers from source with strict compiler warnings/errors showed two warnings.  While none of the issues pointed out by GCC are a problem, this pull request has changes to address the warnings to silence the warning messages.  
There are two warnings being addressed:
velodyne/velodyne_pointcloud/src/lib/rawdata.cc:328:57: error: ‘last_azimuth_diff’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
azimuth_corrected_f = azimuth + (azimuth_diff * ((dsr*VLP16_DSR_TOFFSET) + (firing*VLP16_FIRING_TOFFSET)) / VLP16_BLOCK_TDURATION);
velodyne/velodyne_pointcloud/src/conversions/colors.cc:84:58: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
p.rgb = *reinterpret_cast<float*>(&rainbow[color]);
^
=> GCC Build Warnings

velodyne_driver/launch/nodelet_manager.launch, velodyne_pointcloud/launch/32e_points.launch, velodyne_pointcloud/launch/VLP16_points.launch, velodyne_pointcloud/launch/cloud_nodelet.launch, velodyne_pointcloud/launch/transform_nodelet.launch
Relative to #90 
Add the following options to VLP16 and hdl32 launch files:
- rpm, device_ip, port, read_once, read_fast, repeat_delay
In the 32e_points, there was also no min_range and max_range, I put the same as the vlp16 (though I'm not certain it's correct, 0.4 to 130), and pcap.
Finally, I added the port and device_ip to the nodelet manager.
I am not very familiar with ROS, so am not sure overriding defaults parameters with the same defaults is the best way for some of them, but couldn't find any other way. Please correct me if I am mistaken.
=> Add more options in launch files.

velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h
DISTANCE_MAX and DISTANCE_MAX_UNITS are not used anywhere in the code.
Furthermore, using them would lead to errors as both VLP-64 manuals state that returns above 120 m should not be used. The VLP-32 manual allows 70 m as the maximum valid sensor range.
=> Remove unused constants.

velodyne_driver/src/lib/input.cc
Fix for device_ip filter in InputSocket: initialization of devip_ for correct ip filtering in InputSocket::getPacket.
=> velodyne_driver/src/lib/input.cc : fix for device_ip filter

velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h, velodyne_pointcloud/src/lib/rawdata.cc
At our lab we have had this local change for a while now and thought it might be useful to push out. It's a small tweak to allow us to setup the driver for offline processing from a locally defined calibration file. This method is useful when processing data offline from a bag file, without starting any ros master.
=> Added an interface to set up raw data processing offline

velodyne_driver/src/driver/nodelet.cc, velodyne_pointcloud/src/conversions/cloud_nodelet.cc, velodyne_pointcloud/src/conversions/ringcolors_nodelet.cc, velodyne_pointcloud/src/conversions/transform_nodelet.cc
PLUGINLIB_DECLARE_CLASS has been deprecated in favor of PLUGINLIB_EXPORT_CLASS
http://wiki.ros.org/pluginlib#pluginlib.2BAC8-pluginlib_groovy.Simplified_Export_Macro
=> Modern pluginlib macro

velodyne_pointcloud/src/lib/rawdata.cc
abs is the c version which returns an integer. This is probably not intended here, so use the templated std::abs function.
=> Use std::abs instead of abs

velodyne_laserscan/src/nodelet.cpp
These macros, deprecated for now 8 years, will be removed in the next ROS release (ROS Melodic)
This change will allow the code to keep compiling on future ROS versions
=> update to use non deprecated pluginlib macro

velodyne_laserscan/src/VelodyneLaserScan.cpp
cfg_.resolution is double but fabsf takes a float which may cause truncation of value.
=> Use std::abs instead of fabsf

velodyne_driver/src/driver/driver.cc, velodyne_driver/src/driver/driver.h
Added a periodic update of the diagnostics so that when no data is received at all from the Velodyne, a diagnostic information will be published. The previous implementation would publish diagnostics only on packet reception.
=> Raise diagnostic when no packets are received

velodyne_driver/src/lib/input.cc
Theres a bug when playing back pcap files that contain packets from another udp port (!= 2368). The pcap filter is not applied when the device ip is not set, which leads to incorrect playback of the file.
=> Bugfix: when no device ip is set, we still want to filter by udp port.

velodyne_pointcloud/nodelets.xml
ROS pluginlib only recognizes multiple <library> elements if they are under
<class_libraries> XML root. It silently ignores malformed XMLs with multiple
<library> "root"s and just reads the first one, due to relaxed way tinyxml2 does
parsing. Though if you do `rosrun nodelet declared_nodelets`, the issue is
reported properly.
See also similar issue in https://github.com/ros-perception/perception_pcl/issues/131
=> Fix malformed plugin description XML

velodyne_gps_imu/src/gpsimu_driver.cc
A hard-coded value was used instead of the (same) value that was passed as a function argument.
=> Actually bind to the port that is passed in via function argument

velodyne_gps_imu/src/gpsimu_driver.cc
On my machine (Ubuntu) the error code 995 does not mean a thing.
I hope I translated it correctly to the corresponding Boost.Asio code...
=> Portable handling of ECANCELED

velodyne_driver/src/lib/input.cc
The positive error code that is returned here is not properly handled in the driver.
Now a negative value is returned to indicate an error, as it is also done in InputPCAP::getPacket().
=> Fixed sign error in return value of InputSocket::getPacket()

velodyne_driver/include/velodyne_driver/driver.h, velodyne_driver/src/driver/driver.cc
I had problems running multiple drivers when I used a nodelet manager. So I turned 'last_azimuth' into a member, which solved the issue for me. Also it's a cleaner design.
=> Transform static variable into member

velodyne_driver/CMakeLists.txt, velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/include/velodyne_driver/time_conversion.hpp, velodyne_driver/launch/nodelet_manager.launch, velodyne_driver/src/lib/input.cc, velodyne_driver/tests/timeconversiontest.cpp, velodyne_pointcloud/launch/32e_points.launch, velodyne_pointcloud/launch/64e_S3.launch, velodyne_pointcloud/launch/VLP-32C_points.launch, velodyne_pointcloud/launch/VLP16_points.launch
I'm opening up a couple of PRs for changes we have made to our internal driver so that we can use the public driver again.
This is the first one and it will increase the accuracy of the ros message timestamp by using the GPS provided time. I'm thinking I could add a param to the launch files to enable GPS time instead of removed the prior functionality?
=> Use time within the packet

velodyne_pointcloud/CMakeLists.txt, velodyne_pointcloud/include/velodyne_pointcloud/convert.h, velodyne_pointcloud/include/velodyne_pointcloud/transform.h, velodyne_pointcloud/package.xml, velodyne_pointcloud/src/conversions/convert.cc, velodyne_pointcloud/src/conversions/transform.cc
I'm opening up a couple of PRs for changes we have made to our internal driver so that we can use the public driver again.
This is the last one. This PR adds publishing of diagnostic information. It should be useful to run on a bag with packets to compare performance when changes are made to the convert or transform files. 
Here is an example screenshot:
=> Added diagnostic publishing

velodyne_pointcloud/src/conversions/transform.cc
Closes #235 
In my original PR I had a frame_id and fixed_frame_id. When I removed the fixed_frame_id I missed some changes causing the output frame to be map. Now the transformed pointcloud output is in the same frame as the normal pointcloud. I created a launch file to switch between them and confirm this.
/velodyne_points
- regular rings
/velodyne_points_corrected
- Transformed (corrected) rings
=> set correct output frame

velodyne_driver/cfg/VelodyneNode.cfg, velodyne_driver/include/velodyne_driver/driver.h, velodyne_driver/src/driver/driver.cc
This will allow polling to be disabled when the device has been disabled
in some way. Specifically this is interesting when the rpm is set to 0
when not is use. This also adds a mask value for the time_offset so that
it won't be touched if it wasn't reconfigured.
=> driver: add enabled reconfigure param

velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
As "cloud.width" has not been assigned, it is 0 here, which makes "cloud.row_step" 0. Another option is moving the calculation of "cloud.row_step"  to function "setup".
=> bug fix for row step

velodyne_pointcloud/src/lib/calibration.cc
Both min_intensity and max_intensity create a temporary object,
and then store a pointer to the object.  The object then goes
out of scope, and the pointer is dereferenced.  Fix this by
just not using the temporary at all and instead doing the
float conversion directly, which is less code and more correct.
This is the equivalent of #239 for ROS 2.
=> Dashing: Fix dead pointers in calibration.cc.

velodyne_pointcloud/src/lib/calibration.cc, velodyne_pointcloud/src/lib/rawdata.cc
clang static analysis pointed out that distance is stored
to, but never read.  It looks like it is probably the result
of a bad merge, so just remove the unused variable.  Also
do a bit of style cleanup while we are in here.
=> Dashing: Remove dead store from rawdata.cc

velodyne_pointcloud/src/lib/rawdata.cc
It looks like probably the result of a bad merge; the distance
variable is never used in the outer scope, so just remove it.
=> Remove a dead store from rawdata.cc.

velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
Wouldn't compile on MacOSX Mojave without this change. The default "ratio" is different when omitting the second template argument (nanoseconds).
Off topic: I've been trying to compile the past couple of weeks, without success. It's unfortunately not possible to compile with Mojave and Xcode. Needed to get rid of Xcode :( for it to work (same issue as seen here https://github.com/PointCloudLibrary/pcl/issues/2601#issuecomment-486889884 and in many other places online) I hope someone finds a solution for that soon...
=> Dashing: fixed timpepoint issue

velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/src/driver/driver.cc, velodyne_driver/src/driver/velodyne_node.cc, velodyne_driver/src/lib/input.cc, velodyne_pointcloud/src/conversions/convert_node.cc, velodyne_pointcloud/src/conversions/transform_node.cc
Ideally, the classes in [input.cc](https://github.com/ros-drivers/velodyne/blob/dashing-devel/velodyne_driver/src/lib/input.cc) would have no knowledge of ROS at all.  This would make them more independent and able to be unit tested a bit more easily.  This PR goes some way towards doing that by removing all of the `get_parameter` calls in input.cc, and instead passes those values in when the classes are constructed.  After this PR, the only remaining uses for the node handle inside of `input.cc` is for the logging; I'll consider how to deal with that better later.
=> Dashing: Start removing node handle from input.cc

velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/src/driver/driver.cc, velodyne_laserscan/include/velodyne_laserscan/velodyne_laserscan.h, velodyne_laserscan/src/velodyne_laserscan.cpp, velodyne_pointcloud/include/velodyne_pointcloud/calibration.h, velodyne_pointcloud/include/velodyne_pointcloud/convert.h, velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h, velodyne_pointcloud/include/velodyne_pointcloud/organized_cloudXYZIR.h, velodyne_pointcloud/include/velodyne_pointcloud/pointcloudXYZIR.h, velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h, velodyne_pointcloud/include/velodyne_pointcloud/transform.h, velodyne_pointcloud/src/conversions/convert.cc, velodyne_pointcloud/src/conversions/organized_cloudXYZIR.cc, velodyne_pointcloud/src/conversions/pointcloudXYZIR.cc, velodyne_pointcloud/src/conversions/transform.cc, velodyne_pointcloud/src/lib/calibration.cc, velodyne_pointcloud/src/lib/rawdata.cc
This is a somewhat large and subjective PR, but the main goal here is to reduce the amount of duplicate storage of configuration parameters in the classes that make up the velodyne_pointcloud code.  The main benefits of doing so are:
1.  Helps with readability
1.  Makes it easier to implement on-the-fly parameter changes (which will come in a follow-on PR)
1.  Reduces memory footprint slightly
There is also a bunch of cleanup of code in this PR, along with the removal of some unused functions.  My suggestion for reviewing this is commit-by-commit, since each commit is fairly small and does one logical thing.  @JWhitleyAStuff if you'd prefer a couple of smaller PRs, I can do that too; just let me know.
Thanks!
=> Dashing: Remove redundant storage of configuration data

velodyne_driver/src/driver/velodyne_node.cc
As a follow-up to #213 and the implementation in #216, I added support for not exiting the driver on poll timeouts to the node as well. I assume there is no specific reason why the node should behave differently than the nodelet here.
=> when device poll timeouts, do not stop node

velodyne_pointcloud/src/conversions/convert.cc, velodyne_pointcloud/src/conversions/transform.cc
When running as a composed node in a container, the usual `get_subscription_count()` method may return 0; it's necessary to also check `get_intra_process_subscription_count()`.
Distribution Statement A; OPSEC #2893
Signed-off-by: P. J. Reed <preed@swri.org>
=> Check for intra-process subscribers

velodyne_pointcloud/src/lib/rawdata.cc
The current implementation in `rawdata.cc` gets the `model` parameter from a public node handle which is referencing a static node name. Since the node name is dynamic and can be namespaced, this rarely works. Changed to use the passed-in private node handle to get the parameter dynamically.
=> Getting model param for timings from private node handle.

velodyne_pointcloud/launch/VLP-32C_points.launch
This model supports ranges of 200m, not 130 as is the default
Completes: #315
=> Increase VLP32-C max range

velodyne_laserscan/src/velodyne_laserscan.cpp
Precisely what the title says. I stumbled upon this while trying to use the `velodyne_laserscan` node along with `velodyne` Gazebo plugins. `r` would always be `0`. I *believe* (do correct me if I'm wrong) that this is what the original author had in mind. 
Tagging @clalancette for awareness.
=> Fix ring retrieval from float pointcloud iterator.

velodyne_driver/package.xml, velodyne_laserscan/package.xml
Ensure that we depend on ament_cmake_ros as appropriate.
=> Fix dependencies in package.xml

velodyne_pointcloud/package.xml, velodyne_pointcloud/src/lib/CMakeLists.txt, velodyne_pointcloud/tests/CMakeLists.txt
1.  Ensure that package.xml lists all of the test dependencies
needed.
2.  Ensure that velodyne_cloud_types depends on rclcpp.
3.  Make sure test_row_step depends on geometry_msgs and
sensor_msgs.  It doesn't have any *direct* dependencies on
them, but it includes datacontainerbase.hpp which does have
direct dependencies.
=> More fixing of dependencies.

velodyne_pointcloud/launch/32e_points.launch, velodyne_pointcloud/launch/64e_S3.launch, velodyne_pointcloud/launch/VLP-32C_points.launch, velodyne_pointcloud/launch/VLP16_points.launch, velodyne_pointcloud/launch/cloud_nodelet.launch, velodyne_pointcloud/src/conversions/convert.cc
Several parameters were not being correctly passed to the `Convert` object causing things like the `frame_id` to be ignored. This PR fixes that issue.
=> Passing fixed_frame and target_frame to Convert object.

.circleci/config.yml, velodyne_pointcloud/tests/test_calibration.cpp
This will set CI to target Noetic on `master`. The `melodic-devel` branch is now for Melodic and before.
=> CI: Target Noetic on Master

velodyne_pcl/CMakeLists.txt, velodyne_pcl/README.md, velodyne_pcl/include/velodyne_pcl/point_types.h, velodyne_pcl/package.xml, velodyne_pointcloud/include/velodyne_pointcloud/organized_cloudXYZIRT.h, velodyne_pointcloud/include/velodyne_pointcloud/pointcloudXYZIRT.h, velodyne_pointcloud/include/velodyne_pointcloud/transform.h, velodyne_pointcloud/src/conversions/CMakeLists.txt, velodyne_pointcloud/src/conversions/convert.cc, velodyne_pointcloud/src/conversions/organized_cloudXYZIR.cc, velodyne_pointcloud/src/conversions/organized_cloudXYZIRT.cc, velodyne_pointcloud/src/conversions/pointcloudXYZIRT.cc, velodyne_pointcloud/src/conversions/transform.cc
Regrading #287 The `velodyne_pcl` ROS package restores the conversion file `point_types.h`.
The README explains how to use it.
The following has been done:
- Fixed assignment of the time value in the organized point cloud container
- Added `velodyne_pcl` ROS package with the `point_types.h` header file.
- Added a RAEDME.md file to explain how to convert velodyne ROS point clouds to PCL
- Renamed both containers to cover the previously added time property.
=> Velodyne pcl

velodyne_pcl/include/velodyne_pcl/point_types.h
Fixes an issue where the POINT_CLOUD_REGISTER_POINT_STRUCT function was using the old PointXYZIR and not PointXYZIRT.
=> Fix typo in velodyne_pcl/point_types.h

velodyne_pointcloud/src/lib/rawdata.cc
This is a backport of PR #360 to melodic-devel 
* Set NaN in ordered point cloud in case of no return
Signed-off-by: Thomas Nuernberg  <thomas.nuernberg@de.bosch.com>
* Adapt to current master
Signed-off-by: Thomas Nuernberg <thomas.nuernberg@de.bosch.com>
* consider min/max angle and timing_offsets also in organized mode
Signed-off-by: Scherer Sebastian (CR/AAS3) <sebastian.scherer2@de.bosch.com>
Co-authored-by: Nuernberg Thomas (CR/AEV4) <thomas.nuernberg@de.bosch.com>
=> Add invalid points in organized cloud (Backport of #360 to melodic-devel )

velodyne_driver/src/driver/driver.cc, velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h, velodyne_pointcloud/src/lib/rawdata.cc
Add Support for the new Velodyne Alpha Prime with 128 lasers.
=> Add support for the velodyne Alpha Prime

velodyne_driver/src/driver/driver.cpp, velodyne_driver/src/lib/input.cpp
These changes will allow velodyne to compile without warnings
on Rolling (soon to be Galactic).  The changes are also backwards
compatible to Foxy if we want to backport them.
@JWhitleyWork This should be a quick review, thanks in advance!
=> Minor fixes to string formatting.

velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
The PointCloud2 msg will be then valid: http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointCloud2.html
Referred issues:
* https://answers.ros.org/question/377470/rtabmap-icp_odometrycpp453callbackcloud-fatal-error/
* http://official-rtab-map-forum.67519.x6.nabble.com/Condition-scan3dMsg-data-size-scan3dMsg-row-step-scan3dMsg-height-not-met-td7852.html
=> Fixed row_step=0 when init_width=0 (dense cloud)

velodyne_driver/include/velodyne_driver/input.h, velodyne_driver/include/velodyne_driver/time_conversion.hpp, velodyne_driver/launch/nodelet_manager.launch, velodyne_driver/src/lib/input.cc, velodyne_pointcloud/launch/32e_points.launch, velodyne_pointcloud/launch/64e_S3.launch, velodyne_pointcloud/launch/VLP-32C_points.launch, velodyne_pointcloud/launch/VLP16_points.launch
This pull request continues on the work of #58 to add the ability to timestamp the published topics using the timestamp in the PCAP headers. I have also added the GPS time correction from #222 so that the PCAP ethernet header time can be corrected using the GPS time inside the Velodyne packet.
It handles the following combinations of the time parameters:
- `gps_time == false` and `pcap_time == false`: Sets time to `ros::Time::now()`
- `gps_time == false` and `pcap_time == true`: Sets time to the time in the PCAP ethernet headers
- `gps_time == true` and `pcap_time == false`: Sets time to `ros::Time::now()`, because this is an invalid combination of parameters
- `gps_time == true` and `pcap_time == true`: Sets time to the time in the PCAP ethernet headers and then uses the function from …
=> PCAP timestamps & PCAP+GPS timestamps

velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
See this comment: https://github.com/ros-drivers/velodyne/pull/404#issuecomment-840144795
The PointCloud2 msg will be then valid: http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointCloud2.html
Referred issues:
* https://answers.ros.org/question/377470/rtabmap-icp_odometrycpp453callbackcloud-fatal-error/
* http://official-rtab-map-forum.67519.x6.nabble.com/Condition-scan3dMsg-data-size-scan3dMsg-row-step-scan3dMsg-height-not-met-td7852.html
=> Fixed row_step=0 when init_width=0 (dense cloud) [melodic-devel]

velodyne_driver/include/velodyne_driver/time_conversion.hpp, velodyne_driver/src/lib/input.cc
This PR fixes a problem introduced with PR #384 that broke compilation of the tests for velodyne_driver. Maybe @HMellor and @JWhitleyWork can have a brief look.
The tests actually failed to compile there as well, but for some reason the CI did not catch this as a failure:
https://github.com/ros-drivers/velodyne/runs/2571172566?check_suite_focus=true
Try the following to reproduce:
```
catkin build velodyne_driver --catkin-make-args run_tests
```
which leads to:
```
[ 75%] Built target velodyne_driver_tests_vlp16.pcap
[ 75%] Built target velodyne_driver_tests_class.pcap
In file included from /home/user/catkin_ws/src/velodyne/velodyne_driver/tests/timeconversiontest.cpp:33:
/home/user/catkin_ws/src/velodyne/velodyne_driver/include/velodyne_driver/time_conversion.hpp: In function ‘ros::Time …
```
=> add missing include to pcap.h that prevents tests from being built

velodyne_pointcloud/src/lib/rawdata.cc
This PR fixes a bug in `RawData::unpack_vls128()` which leads to the driver crashing when `organize_cloud` is enabled.
*Steps to reproduce:*
* Start the driver with organize_cloud set to true:
`roslaunch velodyne_pointcloud VLS128_points.launch organize_cloud:=true`
* Subscribe to `velodyne_points`
* The driver will crash with `[velodyne_nodelet_manager-1] process has died `
*Explanation and fix:*
* The current implementation of `RawData::unpack_vls128()` starts a new line of the point cloud after each block. A block in case of the vls128 , however, only contains data from a bank of 32 of the 128 lasers. A line of the point cloud must therefore consist of four blocks, i.e. data of four banks.
* The current implementation crashes because it tries to write far beyond the memory allocated …
=> fix crashes when using vls128 in organized mode

velodyne_driver/src/lib/input.cc
The Boston Dynamics Spot Core with the EAP (Enhanced Autonomy Package) version also binds to UDP port 2368 in its velodyne service, and without this update the ROS velodyne driver cannot bind to the port. It gives "Bind address already in use" warning and a "Cannot poll device" error. The reason is that, without setting the socket binding option to reuseable, it  locks away the UDP port from every other concurrent connection.
=> reuse Velodyne UDP port

velodyne/launch/velodyne-all-nodes-VLP16-composed-launch.py, velodyne/launch/velodyne-all-nodes-VLP16-launch.py, velodyne/launch/velodyne-all-nodes-VLP32C-composed-launch.py, velodyne/launch/velodyne-all-nodes-VLP32C-launch.py, velodyne_driver/launch/velodyne_driver_node-VLP16-composed-launch.py, velodyne_driver/launch/velodyne_driver_node-VLP16-launch.py, velodyne_driver/launch/velodyne_driver_node-VLP32C-composed-launch.py, velodyne_driver/launch/velodyne_driver_node-VLP32C-launch.py, velodyne_laserscan/launch/velodyne_laserscan_node-composed-launch.py, velodyne_laserscan/launch/velodyne_laserscan_node-launch.py, velodyne_pointcloud/launch/velodyne_convert_node-VLP16-composed-launch.py, velodyne_pointcloud/launch/velodyne_convert_node-VLP16-launch.py, velodyne_pointcloud/launch/velodyne_convert_node-VLP32C-composed-launch.py, velodyne_pointcloud/launch/velodyne_convert_node-VLP32C-launch.py, velodyne_pointcloud/launch/velodyne_transform_node-VLP16-composed-launch.py, velodyne_pointcloud/launch/velodyne_transform_node-VLP16-launch.py, velodyne_pointcloud/launch/velodyne_transform_node-VLP32C-composed-launch.py, velodyne_pointcloud/launch/velodyne_transform_node-VLP32C-launch.py
Some of the argument names are deprecated in Foxy and do not work in Galactic. Eg. `node_executable` should now be just `executable`. After some testing with a VLP-16 on ROS2 Galactic the updated launch files worked as expected and the nodes were launched.
=> Replace deprecated argument names in launch

velodyne_driver/config/VLP16-velodyne_driver_node-params.yaml, velodyne_driver/config/VLP32C-velodyne_driver_node-params.yaml, velodyne_driver/include/velodyne_driver/driver.hpp, velodyne_driver/src/driver/driver.cpp
ros2 porting for #283
a part of https://github.com/ros-drivers/velodyne/pull/434
=> Add option timestamp first packet

velodyne_pointcloud/src/lib/CMakeLists.txt
On MacOS building the ros2 branch fails with the following error:
```
--- stderr: velodyne_pointcloud
Undefined symbols for architecture x86_64:
"YAML::InvalidNode::~InvalidNode()", referenced from:
YAML::Node const YAML::Node::operator[]<char [9]>(char const (&) [9]) const in calibration.cpp.o
YAML::Node const YAML::Node::operator[]<char [15]>(char const (&) [15]) const in calibration.cpp.o
YAML::Node const YAML::Node::operator[]<char [16]>(char const (&) [16]) const in calibration.cpp.o
YAML::Node const YAML::Node::operator[]<char [28]>(char const (&) [28]) const in calibration.cpp.o
YAML::Node const YAML::Node::operator[]<char [18]>(char const (&) [18]) const in calibration.cpp.o
YAML::Node const YAML::Node::operator[]<char [23]>(char const (&) [23]) const in calibration.cpp.o …
```
=> Link against yaml-cpp

velodyne_pcl/include/velodyne_pcl/point_types.h
Resolves https://github.com/ros-drivers/velodyne/issues/445.
Not really a necessary change, but it gets rid of deprecated build warnings, and is more explicit about the fact that it isn't using PCL's (now deprecated) definition of `uint16_t`.
=> Use std::uint16_t to reduce build warnings from PCL

velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h, velodyne_pointcloud/src/lib/rawdata.cc
Currently when using the offline setup, it does not build the per-point timing offsets which means when unpacking the packets in the offline mode, you cannot timestamp each point with its packet time.
This PR does the following:
- call buildTimings from setupOffline function
- add model to setupOffline interface
- set config model param which is needed by buildTimings
=> fix timing bug with offline use

velodyne_driver/src/driver/driver.cc, velodyne_driver/src/lib/input.cc
Commits d016fcc336a0c4e49423c966aa3acc0477848644 and 15771a42cf91ffaa946846174c639edf1056b693 in combination turned packet timeouts into an error that stops the node from responding. This patch restores the original behavior.
Changed getPacket() to return 0 on timeout and 1 on success. 
Updated VelodyneDriver::poll() accordingly.
=> Fix non-responsive node on packet timeout

velodyne_laserscan/src/velodyne_laserscan.cpp
By rounding the array size instead of truncating it, the laser scan topic is compatible with slam_toolbox and can be used to create maps.
=> using std::round to calculate the scan array size

velodyne_pointcloud/params/64e_s2.1-sztaki.yaml, velodyne_pointcloud/params/64e_s3-xiesc.yaml, velodyne_pointcloud/params/64e_utexas.yaml, velodyne_pointcloud/scripts/add_two_pt.py, velodyne_pointcloud/scripts/gen_calibration.py, velodyne_pointcloud/tests/test_calibration.cpp
In order to take into account *HDL-64* correction_{x,y}, related to 2012 merge:
https://github.com/ros-drivers/velodyne/blob/1.7.0/velodyne_pointcloud/src/lib/rawdata.cc#L438
https://github.com/ros-drivers/velodyne/blob/1.7.0/velodyne_pointcloud/src/lib/calibration.cc#L70
see issues: #109 #295
and commit: f30d68735c47312aa73d29203ddb16abc01357f4
=> [velodyne_pointcloud] add_two_pt scripts

velodyne_driver/CMakeLists.txt, velodyne_driver/package.xml
No need to have `roslint` actually ending up in production robots.
=> roslint can be a test-depend

.github/workflows/basic-build-ci.yaml, velodyne_driver/include/velodyne_driver/driver.hpp, velodyne_driver/include/velodyne_driver/input.hpp, velodyne_driver/include/velodyne_driver/time_conversion.hpp, velodyne_driver/src/driver/driver.cpp, velodyne_driver/src/driver/velodyne_node.cpp, velodyne_driver/src/lib/input.cpp, velodyne_driver/tests/timeconversiontest.cpp, velodyne_laserscan/src/node.cpp, velodyne_laserscan/src/velodyne_laserscan.cpp, velodyne_laserscan/tests/system.cpp, velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.hpp, velodyne_pointcloud/include/velodyne_pointcloud/organized_cloudXYZIRT.hpp, velodyne_pointcloud/include/velodyne_pointcloud/pointcloudXYZIRT.hpp, velodyne_pointcloud/include/velodyne_pointcloud/rawdata.hpp, velodyne_pointcloud/include/velodyne_pointcloud/transform.hpp, velodyne_pointcloud/src/conversions/transform.cpp, velodyne_pointcloud/src/conversions/transform_node.cpp, velodyne_pointcloud/src/lib/calibration.cpp, velodyne_pointcloud/src/lib/organized_cloudXYZIRT.cpp, velodyne_pointcloud/src/lib/pointcloudXYZIRT.cpp, velodyne_pointcloud/src/lib/rawdata.cpp, velodyne_pointcloud/tests/test_calibration.cpp
Update CI on the `humble-devel` branch to actually build for Humble (what a thought!).
=> Update humble ci

velodyne/launch/velodyne-all-nodes-VLS128-composed-launch.py, velodyne/launch/velodyne-all-nodes-VLS128-launch.py, velodyne_driver/config/VLS128-velodyne_driver_node-params.yaml, velodyne_driver/launch/velodyne_driver_node-VLS128-composed-launch.py, velodyne_driver/launch/velodyne_driver_node-VLS128-launch.py, velodyne_driver/src/driver/driver.cpp, velodyne_pointcloud/config/VLS128-velodyne_transform_node-params.yaml, velodyne_pointcloud/include/velodyne_pointcloud/rawdata.hpp, velodyne_pointcloud/launch/velodyne_transform_node-VLS128-composed-launch.py, velodyne_pointcloud/launch/velodyne_transform_node-VLS128-launch.py, velodyne_pointcloud/params/VLS128.yaml, velodyne_pointcloud/src/conversions/transform.cpp, velodyne_pointcloud/src/lib/rawdata.cpp
* Update rolling ci (#512)
Fix Rolling CI and associated linter errors.
* Add support for the velodyne Alpha Prime (#370)
* Add support for the velodyne Alpha Prime
* Change packet rate for the VLS128 according to the times specified in the manual
* Organize setup functions to avoid code duplication. Add a constant for the model ID of the VLS128.
* Use the defined constants to calculate the time offset of the points for the VLS128
* Add VLS128 launch and calibration file (#382)
* vls128: add line only once all four banks are processed (#413)
* fix: apply uncrustify
* Fixing incorrect type in velodyne_pointcloud.
* Fixed non working vls128 fork
* Added organized cloud compliance and remove some useless code
* Corrected the azimuth offset calculation and put the declation of variable where …
=> feat: support vls128 for ros2 (#493)

.github/workflows/basic-build-ci.yaml
Since the `ros2` branch currently targets the latest release plus `rolling`, this adds CI jobs to cover both environments. From my experience, there usually aren't too many conflicts between them, especially immediately after a release.
=> Add iron CI to ros2 branch

velodyne_pointcloud/params/VLP16db.yaml
According to the [VLP-16 User Manual](https://velodynelidar.com/wp-content/uploads/2019/12/63-9243-Rev-E-VLP-16-User-Manual.pdf) (page 54) lidar lasers have vertical offsets in their position. This PR corrects the calibration file.
=> Add vert offset corrections to VLP16 calib file

velodyne_pointcloud/params/64e_s2.1-sztaki.yaml, velodyne_pointcloud/params/64e_s3-xiesc.yaml, velodyne_pointcloud/params/64e_utexas.yaml, velodyne_pointcloud/scripts/add_two_pt.py, velodyne_pointcloud/scripts/gen_calibration.py, velodyne_pointcloud/tests/test_calibration.cpp
* pull: https://github.com/ros-drivers/velodyne/pull/473
* issues: https://github.com/ros-drivers/velodyne/issues/109 https://github.com/ros-drivers/velodyne/issues/295
* commit: https://github.com/ros-drivers/velodyne/commit/f30d68735c47312aa73d29203ddb16abc01357f4
=> Feature script add two pt ros2
