ros-drivers/velodyne

- velodyne_driver/CMakeLists.txt
- velodyne_driver/src/driver/driver.cc
- velodyne_driver/tests/pcap_vlp16_node_hertz.test
- velodyne_driver/tests/pcap_vlp16_nodelet_hertz.test
- velodyne_pointcloud/CMakeLists.txt
- velodyne_pointcloud/include/velodyne_pointcloud/calibration.h
- velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h
- velodyne_pointcloud/launch/VLP16_points.launch
- velodyne_pointcloud/params/VLP16db.yaml
- velodyne_pointcloud/src/lib/calibration.cc
- velodyne_pointcloud/src/lib/rawdata.cc
- velodyne_pointcloud/tests/cloud_node_vlp16_hz .test
- velodyne_pointcloud/tests/cloud_node_vlp16_hz.test
- velodyne_pointcloud/tests/cloud_nodelet_vlp16_hz.test
Modifications to support the VLP16 including pointcloud processing.
I have the a PCAP file if there is no hardware available to test. I have tested with the units we have inhouse. Also added azimuth correction for inter block/firing dsr#.
Added launch file and calibration for the VLP16 as well.
> adding driver and pointcloud support for the VLP16

- .travis.yml
@jack-oquin what do you think about adding travis-ci for pull requests?
> add travis pr testing

- velodyne_driver/src/driver/driver.cc
Also verified with sensor. It reduced overlap in the pointcloud
User manual:
http://velodynelidar.com/docs/manuals/63-9243%20Rev%20B%20User%20Manual%20and%20Programming%20Guide,VLP-16.pdf
Page #5
> updated VLP-16 packet rate from user manual.

- velodyne_pointcloud/src/lib/rawdata.cc
intensity and VPoint::intensity are both of type float.
> Fix misleading typecasts.

- velodyne/package.xml
- velodyne_laserscan/CMakeLists.txt
- velodyne_laserscan/cfg/VelodyneLaserScan.cfg
- velodyne_laserscan/nodelets.xml
- velodyne_laserscan/package.xml
- velodyne_laserscan/src/VelodyneLaserScan.cpp
- velodyne_laserscan/src/VelodyneLaserScan.h
- velodyne_laserscan/src/node.cpp
- velodyne_laserscan/src/nodelet.cpp
- velodyne_laserscan/tests/CMakeLists.txt
- velodyne_laserscan/tests/lazy_subscriber.cpp
- velodyne_laserscan/tests/lazy_subscriber_node.test
- velodyne_laserscan/tests/lazy_subscriber_nodelet.test
- velodyne_laserscan/tests/system.cpp
- velodyne_laserscan/tests/system_node.test
- velodyne_laserscan/tests/system_nodelet.test
- velodyne_pointcloud/launch/32e_points.launch
- velodyne_pointcloud/launch/VLP16_points.launch
- velodyne_pointcloud/launch/laserscan_nodelet.launch
- velodyne_pointcloud/package.xml
- velodyne_pointcloud/tests/CMakeLists.txt
- velodyne_pointcloud/tests/two_nodelet_managers.test
Extract a single ring from the [PointCloud2](http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html) topic ```velodyne_points``` and publish a [LaserScan](http://docs.ros.org/api/sensor_msgs/html/msg/LaserScan.html) topic to ```scan```
* Fast and efficient algorithm using ```sensor_msgs/point_cloud2_iterator.h``` (no PCL)
* Automatically select ring for known devices (VLP-16, HDL-32E, HDL-64E)
* Lazy subscribers that don't even subscribe until the scan output is requested
* Integrated into existing launch files
> Added velodyne_laserscan package

- velodyne_driver/src/driver/driver.cc
Following https://github.com/ros-drivers/velodyne/issues/142 adding the correct packet_rate
> Fix packet rate for the Velodyne 32C

- velodyne_driver/src/driver/driver.cc
- velodyne_pointcloud/src/lib/rawdata.cc
This pull request should be able to fix issue #174.
> Bugfix issue #174

- velodyne_pointcloud/include/velodyne_pointcloud/calibration.h
- velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h
- velodyne_pointcloud/src/conversions/convert.cc
- velodyne_pointcloud/src/lib/calibration.cc
- velodyne_pointcloud/src/lib/rawdata.cc
Supersedes PR #155 - all work done by @facontidavide.
> Avoid unnecessary computation

- velodyne_driver/src/driver/driver.cc
- velodyne_pointcloud/include/velodyne_pointcloud/rawdata.h
- velodyne_pointcloud/launch/64e_S3.launch
- velodyne_pointcloud/launch/cloud_nodelet.launch
- velodyne_pointcloud/params/64e_s3-xiesc.yaml
- velodyne_pointcloud/src/lib/rawdata.cc
add support for 64E_S3. And the current version discards the "Last return" in S3 dual return systems. I will add the support for all mode in dual return latter when I confirm the protocol.
> add support for 64E_S3

- velodyne_driver/src/driver/nodelet.cc
> Testing reporting error instead of stopping node on disconnect.

- .circleci/config.yml
- velodyne_driver/CMakeLists.txt
- velodyne_laserscan/CMakeLists.txt
- velodyne_pointcloud/CMakeLists.txt
Thanks to @andre-nguyen for the suggestions!
> CI: Adding roslint as separate step. Limiting output of catkin build.

- velodyne_driver/CMakeLists.txt
- velodyne_laserscan/CMakeLists.txt
- velodyne_pointcloud/CMakeLists.txt
This avoids lowering the standard if it is already C++14
> Set minimum C++ standard to C++11

- velodyne_driver/src/driver/driver.cc
This ensures that we get a full scan rotation, not just
a somewhat variable number of packets.
@JWhitleyAStuff While I do like this default strategy better, in my testing the cut_angle feature didn't actually work for values less than 2*PI (or, at least, didn't work as I expected it to).  As far as I could tell, it never cut off anything; it always collected a full rotation.  And looking at the code in `poll`, this makes sense; there is no facility for "skipping" packets once we have passed the cut angle.  Am I misunderstanding the purpose of cut_angle?
Fixes #262
> Dashing: Switch to using the cut angle by default.

- velodyne_driver/mainpage.dox
- velodyne_msgs/mainpage.dox
- velodyne_pointcloud/mainpage.dox
> Dashing: Update the documentation for ROS 2.

- velodyne_pointcloud/src/conversions/convert.cc
- velodyne_pointcloud/src/conversions/transform.cc
> Dashing: Switch organize_cloud to true by default.

- velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
- velodyne_pointcloud/src/conversions/transform.cc
> fix for #267, transform each packet

- velodyne_laserscan/CMakeLists.txt
- velodyne_pointcloud/CMakeLists.txt
- velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h
- velodyne_pointcloud/tests/CMakeLists.txt
- velodyne_pointcloud/tests/test_row_step.cpp
We were setting it up too early, so that it was always zero.
Instead move it into the setup once we know the width of
the cloud.
@JWhitleyAStuff FYI
> Dashing: Properly setup the row_step.

- CONTRIBUTING.md
- LICENSE
- velodyne_driver/CMakeLists.txt
- velodyne_driver/include/velodyne_driver/driver.hpp
- velodyne_driver/include/velodyne_driver/input.hpp
- velodyne_driver/include/velodyne_driver/time_conversion.hpp
- velodyne_driver/launch/velodyne_driver_node-VLP16-composed-launch.py
- velodyne_driver/launch/velodyne_driver_node-VLP16-launch.py
- velodyne_driver/package.xml
- velodyne_driver/src/driver/driver.cpp
- velodyne_driver/src/driver/velodyne_node.cpp
- velodyne_driver/src/lib/CMakeLists.txt
- velodyne_driver/src/lib/input.cpp
- velodyne_driver/tests/timeconversiontest.cpp
Adds ROS2 common linters. Fixes all suggestions. Re-enables `diagnostic_updater`.
> ROS2: Add Linters to velodyne_driver

- velodyne_driver/include/velodyne_driver/driver.hpp
- velodyne_driver/launch/velodyne_driver_node-VLP16-composed-launch.py
- velodyne_driver/src/driver/driver.cpp
- velodyne_laserscan/launch/velodyne_laserscan_node-composed-launch.py
- velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.hpp
- velodyne_pointcloud/launch/velodyne_convert_node-VLP16-composed-launch.py
- velodyne_pointcloud/launch/velodyne_convert_node-VLP16-launch.py
- velodyne_pointcloud/launch/velodyne_transform_node-VLP16-composed-launch.py
- velodyne_pointcloud/launch/velodyne_transform_node-VLP16-launch.py
- velodyne_pointcloud/scripts/gen_calibration.py
This PR has a bunch of fixes that I needed to make the current Dashing actually work with my VLP-16.  With all of these in place, I'm now able to make this produce pointclouds as before.  @JWhitleyAStuff  please take a look, thanks!
> Dashing fixes

- velodyne_pointcloud/include/velodyne_pointcloud/convert.hpp
- velodyne_pointcloud/include/velodyne_pointcloud/transform.hpp
- velodyne_pointcloud/src/conversions/convert.cpp
- velodyne_pointcloud/src/conversions/transform.cpp
- velodyne_pointcloud/src/lib/rawdata.cpp
- Get rid of the last users of new in the codebase
- Get rid of the users of 'using' in the codebase
- Rename 'calibrationFile' -> 'calibration_file'
> A few more minor style updates.

- velodyne_laserscan/src/velodyne_laserscan.cpp
Untested, but it's just a simple change.
Addresses issue #292
> Add laserscan support for new PointXYZIR structure

- velodyne_pointcloud/launch/VLS128_points.launch
- velodyne_pointcloud/params/VLS128.yaml
ROS1 driver has already supported VLS128 AP, but there are no calibration file and launch file, so I added them.
> Add VLS128 launch and calibration file

- .github/workflows/basic-build-ci.yaml
> Fix action CI.

- velodyne_pointcloud/config/VLP32C-velodyne_convert_node-params.yaml
- velodyne_pointcloud/config/VLP32C-velodyne_transform_node-params.yaml
ros2 porting for #323
a part of #434
> Increase the max_range of the 32C launch file (#323)

- velodyne_driver/src/lib/input.cpp
- velodyne_laserscan/src/velodyne_laserscan.cpp
ros2 porting for #427
a part of #434
> reuse Velodyne UDP port (#427)

- velodyne/package.xml
- velodyne_driver/package.xml
- velodyne_laserscan/package.xml
- velodyne_msgs/package.xml
- velodyne_pointcloud/package.xml
> Updating maintainer email address.

- velodyne_pointcloud/config/VLP16-velodyne_convert_node-params.yaml
- velodyne_pointcloud/config/VLP32C-velodyne_convert_node-params.yaml
- velodyne_pointcloud/src/conversions/convert.cpp
A part of #434
ros2 port of #330
> Passing fixed_frame and target_frame to Convert object. (#330)

- velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.hpp
> Fixed row_step=0 when init_width=0 (dense cloud) (#404)

- velodyne_pointcloud/src/lib/rawdata.cpp
> Add invalid points in organized cloud (#360)

- .github/workflows/basic-build-ci.yaml
- velodyne_driver/include/velodyne_driver/driver.hpp
- velodyne_driver/include/velodyne_driver/input.hpp
- velodyne_driver/include/velodyne_driver/time_conversion.hpp
- velodyne_driver/src/driver/driver.cpp
- velodyne_driver/src/driver/velodyne_node.cpp
- velodyne_driver/src/lib/input.cpp
- velodyne_driver/tests/timeconversiontest.cpp
- velodyne_laserscan/src/node.cpp
- velodyne_laserscan/src/velodyne_laserscan.cpp
- velodyne_laserscan/tests/system.cpp
- velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.hpp
- velodyne_pointcloud/include/velodyne_pointcloud/organized_cloudXYZIRT.hpp
- velodyne_pointcloud/include/velodyne_pointcloud/pointcloudXYZIRT.hpp
- velodyne_pointcloud/include/velodyne_pointcloud/rawdata.hpp
- velodyne_pointcloud/include/velodyne_pointcloud/transform.hpp
- velodyne_pointcloud/src/conversions/transform.cpp
- velodyne_pointcloud/src/conversions/transform_node.cpp
- velodyne_pointcloud/src/lib/calibration.cpp
- velodyne_pointcloud/src/lib/organized_cloudXYZIRT.cpp
- velodyne_pointcloud/src/lib/pointcloudXYZIRT.cpp
- velodyne_pointcloud/src/lib/rawdata.cpp
- velodyne_pointcloud/tests/test_calibration.cpp
Fix Rolling CI and associated linter errors.
> Update rolling ci (#512)
